### ISSUE TITLE
Still supported?

### ISSUE THREAD

**Issue by jgeudens** [RicardoNiepel/C4-PlantUML#80]
Hi,

I really love using this library to create C4 models of my applications. But I can't help noticing that the development has stopped. Even simple pull requests with typos aren't merged.

If this library isn't in development anymore, I will need to search for an alternative for future projects.

**Comment by aheil** [comment]
As there are quite a lot of issues and PRs open, I could offer  @RicardoNiepel to take over the maintenance of the extension. I use the extension in three of my university classes on a regularly base and teach the C4 model in my courses, so I have quite some interest in keeping it up and running. I am also have correspondence with Simon Brown from time to time. However, that's completely up to Ricardo. As I also maintain an EIP extension for PlantUML, there is only a little extra effort. @RicardoNiepel, you can of course DM me at Twitter if you are interested.

**Comment by stawirej** [comment]
Hi @aheil, @jgeudens 
did you consider using one of the forks? E.g. you can check my fork: https://github.com/stawirej/C4-PlantUML which is ported to support latest plantuml + some small enhancements.

**Comment by simonbrowndotje** [comment]
I've also had a number of people ask me if development has stopped on this...

**Comment by aheil** [comment]
I would rather push forward and maintain the original Repo instead of a (my or anyone others) fork. Anyway, I have pinged Ricardo directly and just wait for his reply and thoughts. I could imagine priorities have changed.

**Comment by IOrlandoni** [comment]
I have actions for the generation of samples, tests, integration with Percy, and I'm working slowly on resolving all pre-existing issues and PRs [over here](/IOrlandoni/C4-PlantUML) before pushing forward.

**Comment by Potherca** [comment]
This library is included in [the PlantUML-stdlib](https://github.com/plantuml/plantuml-stdlib/), so it works in PlantUML  "out of the box".

In am making an ongoing effort to automate the updating of libraries in the stdlib. As part of that, it is helpful if changes in libraries are tagged. (as requested in #26)

This repo hasn't really been updated for the last two years. There seem to be all sorts of active forks (for example those by @adrianvlupu, @fineconstant, @IOrlandoni, @stawirej, and @xmobe). But since I can only use _one_ repo as source, the ideal way forward would be that activity in this repo is revived.

That is also the only way to avoid different people making the same fix and wasting effort.

So I am really hoping @RicardoNiepel allows others onboard as admins.

If (for whatever reason) that does not happen, rather than push an individual fork, it would be better to collaborate and set up a community-based fork (otherwise the current problem will just repeat itself). 

I've seen a similar thing happen with [bats](https://github.com/sstephenson/bats) which eventually moved to [a community based organisation](https://github.com/bats-core).

On a side-note, for those who weren't aware, @simonbrowndotje (three comment ago) is the one who created [the C4 model](https://c4model.com/) :star_struck:

**Comment by adrianvlupu** [comment]
I try to maintain a working version with different plantUML versions on my fork https://github.com/adrianvlupu/C4-PlantUML. It already includes many of the pull requests on this repo but I kept versioning on branches rather than tags, I think I will change that. 
I haven't been active for quite some time on github due to work, but now I can resurrect it and merge some more pull requests there, maybe at some point everything gets merged. 

I'm really happy the C4 model gets attention 😊. I've been using it at work successfully in combination with plantUML for 2 years now. Let's not let it die.

**Comment by anb0s** [comment]
I've also started with a fork long time ago and then continued to use the one from @adrianvlupu , because lot of PRs integrated there, Thanks :)

It would be good to have new fork for the community to continue work with!

**Comment by RicardoNiepel** [comment]
Ok folks, let me start a separate issue for coordinating it :)

And thank you all for constantly pushing me!
